plugins {
    alias(libs.plugins.spring.boot)
}

dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-server'
    implementation libs.spring.boot.starter.actuator

    testImplementation libs.spring.boot.starter.test
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2024.0.1"
    }
}
