plugins {
    alias(libs.plugins.spring.boot)
}

dependencies {
    implementation project(':common:pickme-common')
    implementation project(':common:pickme-orchestration-api')
    implementation project(':application:pickme-orchestration')
    implementation project(':domain-modules:pickme-order')
    implementation project(':domain-modules:pickme-payment')
    implementation project(':domain-modules:pickme-product')
    implementation project(':domain-modules:pickme-inventory')
    implementation project(':domain-modules:pickme-member')
    implementation project(':domain-modules:pickme-partner')
    implementation project(':domain-modules:pickme-notification')
    implementation project(':domain-modules:pickme-settlement')

    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.data.jpa
    implementation libs.spring.boot.starter.actuator
    implementation libs.micrometer.registry.prometheus
    implementation libs.micrometer.tracing.bridge.brave
    implementation libs.zipkin.reporter.brave

    runtimeOnly libs.postgresql
    runtimeOnly libs.flyway.core
    runtimeOnly libs.flyway.postgresql
    runtimeOnly libs.h2

    testImplementation libs.spring.boot.starter.test
}
