dependencies {
    testImplementation project(':pickme-common')
    testImplementation project(':pickme-order')
    testImplementation project(':pickme-payment')
    testImplementation project(':pickme-product')
    testImplementation project(':pickme-inventory')
    testImplementation project(':pickme-member')
    testImplementation project(':pickme-partner')
    testImplementation project(':pickme-notification')
    testImplementation project(':pickme-settlement')

    testImplementation libs.archunit.junit5
}
