global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pickme-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pickme-app:8080']

  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['kafka-connect:9875']
